

READ_DATA = 2
WRITE_DATA = 3
CW_ANGLE_LIMIT_L = 6
CCW_ANGLE_LIMIT_L = 8
RETURN_LEVEL = 16
GOAL_POSITION = 30
MOVING_SPEED = 32
BIOLOID_FRAME_LENGTH = 33
PRESENT_POSITION = 36
SYNC_WRITE = 131
TORQUE_ENABLE = 24
